version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    depends_on:
      - app
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
